# This is single line comment
print("Restart python learning")
print("on16th of Feb")
print(2 + 2)
print(2 / 2)
print(2 - 2)
print(2 * 2)
print("recreate repo")
print("recreate repo")
print("recreate repo")
